
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GO
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        txtFileName = new javax.swing.JTextField();
        btnBrowes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFileName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 30, 230, -1));

        btnBrowes.setText("Browes");
        btnBrowes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBrowes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowesActionPerformed(evt);
            }
        });
        jPanel1.add(btnBrowes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel1.setText("File Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnProcess.setText("Process Edite");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowesActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(null);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser1.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
          txtFileName.setText(file.getPath());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,null,ex.getMessage(),JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null,"File access cancelled by user.");
    }  
    }//GEN-LAST:event_btnBrowesActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        String filePath = txtFileName.getText();
        Boolean isEmpty = (filePath == null || filePath.trim().isEmpty());
        if(!isEmpty){
            try{
                File file = new File(filePath);
                Editfile(file);

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null,null,ex.getMessage(),JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void Editfile(File file){
        
        try{
            Scanner reader = new Scanner(file);
            String data = "";
            while(reader.hasNextLine()){
                String line = reader.nextLine();
                if(line.length()>3){
                    line = line.substring(0,3);
                }
                data+=line+'\n';
            }
            reader.close();
            
            String OldName = file.getPath();
            
            String strnewname = OldName.substring(0,OldName.lastIndexOf('\\'))+"\\newCurrencydoc.txt";
            
            File newfile = new File(strnewname);

            if(newfile.createNewFile()){
             FileWriter writer = new FileWriter(newfile);
             writer.write(data);
             writer.close();
            }
            
            JOptionPane.showMessageDialog(null,"Process Finshed");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,null,ex.getMessage(),JOptionPane.ERROR_MESSAGE);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowes;
    private javax.swing.JButton btnProcess;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFileName;
    // End of variables declaration//GEN-END:variables

}
